### ISSUE TITLE
Ta bort musiken

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/mentometer#1]
På möten via zoom under corona är musikfunktionen enbart cancerogen

**Comment by oskstr** [comment]
Men visst är hissmusiken off by default? Så det kanske är misstroendeförklaring som är bättre verktyg för det här?

**Comment by elmaxe** [comment]
Jo kanske 😂

Men seriöst så vore det najs med en inställning där man kan stänga av att man inte vill ha musik. Då slipper man bli våldtagen i örat när drek får för sig att sätta på musiken

**Comment by oskstr** [comment]
Det skulle kanske gå att ha likadant som man väljer Färg i Annat 🤔 Då skulle man ju kunna ha olika musik också - eller bara På/Av

**Comment by elmaxe** [comment]
Och kanske volymkontroll
